#######################################################################################
# +---------------------------------------------------------------------------------+ #
# |                                                                                 | #
# |                            LiteBansBridge by Woutzah                            | #
# |                                                                                 | #
# |             Please follow the instructions noted above every setting.           | #
# |      For support, please join the Discord server: https://discord.gg/xPFPYbV    | #
# |                                                                                 | #
# |      Special thanks to MilkyMC for allowing me to publish this custom plugin!   | #
# |                                                                                 | #
# +---------------------------------------------------------------------------------+ #
#######################################################################################

#NOTE: Discord accounts/minecraft accounts need to be linked (with DiscordSRV) in order for this plugin to work.

############################################################
# +------------------------------------------------------+ #
# |                 General Settings                     | #
# +------------------------------------------------------+ #
############################################################

#Paste your discord server id in here
discordserver-id: "689806948362747979"
#This is the channel all moderation performed tasks are broadcasted to
stafflog-textchannel-id: "moderation-log"

#These are warning messages that are sent in a PM to the moderated player
#when a players tries typing in your discord server. Make sure al channels are
#registered in the DiscordSRV config!
dicord-chat-warnings:
  banned:
    - '**---[ You are still banned on ServerName! ]---**\n'
    - 'You can **not** chat in the discord!\n'
    - 'appeal at **appeal.milkymc.net**\n'
    - '**---------------------------------------------**\n'
  muted:
    - '**---[ You are still muted on ServerName! ]---**\n'
    - 'You can **not** chat in the discord!\n'
    - '**--------------------------------------------**\'

#These are warning messages that are sent in a PM to the moderated player
#when a moderation is issued ingame.
litebans-entry-warnings:
  permabanned:
    - '**---[ You have been permabanned on ServerName! ]---**\n'
    - 'You have been **permabanned** by **<issuer>** for **<reason>**\n'
    - 'appeal at **appeal.milkymc.net**\n'
    - '**--------------------------------------------------**\n'
  banned:
    - '**---[ You have been banned on ServerName! ]---**\n'
    - 'You have been banned by **<issuer>** for **<reason>** untill **<untill>**\n'
    - 'appeal at **appeal.milkymc.net**\n'
    - '**---------------------------------------------**\n'
  permamuted:
    - '**---[ You have been permamuted on ServerName! ]---**\n'
    - 'You have been permamuted by **<issuer>** for **<reason>**\n'
    - '**-------------------------------------------------**\n'
  muted:
    - '**---[ You have been muted on ServerName ]---**\n'
    - 'You have been muted by **<issuer>** for **<reason>** untill **<untill>**\n'
    - '**-------------------------------------------**\n'
  warned:
    - '**---[ You have been warned on ServerName! ]---**\n'
    - 'You have been warned by **<issuer>** for **<reason>**\n'
    - '**---------------------------------------------**\n'
  kicked:
    - '**---[ You have been kicked from ServerName! ]---**\n'
    - 'You have been kicked by **<issuer>** for **<reason>**\n'
    - '**-----------------------------------------------**\n'

#These are warning messages that are sent to the stafflog textchannel
#when a moderation is issued on your server.
stafflog-entry-warnings:
  permabanned:
    - '**-----------------------------------------------**\n'
    - '**<player>** has been **permabanned** by **<issuer>** for **<reason>**\n'
    - '**-----------------------------------------------**\n'
  banned:
    - '**-----------------------------------------------**\n'
    - '**<player>** has been banned by **<issuer>** for **<reason>** untill **<untill>**\n'
    - '**-----------------------------------------------**\n'
  permamuted:
    - '**-----------------------------------------------**\n'
    - '**<player>** has been permamuted by **<issuer>** for **<reason>**\n'
    - '**-----------------------------------------------**\n'
  muted:
    - '**-----------------------------------------------**\n'
    - '**<player>** has been muted by **<issuer>** for **<reason>** untill **<untill>**\n'
    - '**-----------------------------------------------**\n'
  warned:
    - '**-----------------------------------------------**\n'
    - '**<player>** has been warned by **<issuer>** for **<reason>**\n'
    - '**-----------------------------------------------**\n'
  kicked:
    - '**-----------------------------------------------**\n'
    - '**<player>** has been kicked by **<issuer>** for **<reason>**\n'
    - '**-----------------------------------------------**\n'
