name: LiteBansBridge
version: 1.5
main: be.woutzah.litebansbridge.LiteBansBridge
api-version: 1.13
authors: [Woutzah]
description: A bridge between litebans and discord!
depend: [LiteBans, DiscordSRV]